# Generated by Django 3.2.9 on 2021-11-27 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.EmailField(max_length=254, unique=True)),
                ('user_name', models.CharField(max_length=250)),
                ('code', models.CharField(max_length=6, unique=True)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('expiry_date', models.DateTimeField()),
            ],
        ),
    ]
