# Generated by Django 3.0.6 on 2020-05-30 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=250)),
                ('body', models.TextField()),
                ('date_asked', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
                ('image_upload', models.ImageField(blank=True, null=True, upload_to='pics')),
                ('faculty', models.CharField(blank=True, max_length=250, null=True)),
                ('tags', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'ordering': ('date_asked',),
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='community.Question')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
