# Generated by Django 3.0 on 2020-05-09 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='premium',
            field=models.BooleanField(default=False),
        ),
    ]
