# Generated by Django 2.2.3 on 2019-11-04 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-publish',)},
        ),
        migrations.AddField(
            model_name='post',
            name='image_upload',
            field=models.ImageField(default=1, upload_to='pics'),
            preserve_default=False,
        ),
    ]
