# Generated by Django 3.0.6 on 2020-06-01 12:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_premium'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premium',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 1, 12, 6, 0, 30829)),
        ),
    ]
