# Generated by Django 3.0 on 2020-01-07 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20191110_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='body_symbol',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
