# Generated by Django 3.0.6 on 2020-06-01 12:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200601_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premium',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 1, 12, 13, 58, 1158)),
        ),
    ]
