# Generated by Django 3.0 on 2020-01-07 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_body_symbol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='body_symbol',
        ),
    ]
