# Generated by Django 3.0.6 on 2020-06-01 12:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200601_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premium',
            name='end',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
