# Generated by Django 3.0 on 2020-05-12 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_broadcast_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tag',
        ),
    ]
