# Generated by Django 3.2.9 on 2021-11-28 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
