# Generated by Django 3.2 on 2021-04-25 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_alter_group_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='description',
            field=models.TextField(default='This group is for 100L faculty of engineering students'),
            preserve_default=False,
        ),
    ]
