# Generated by Django 3.2.7 on 2021-09-06 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_alter_interest_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='keytags',
            field=models.TextField(db_index=True, default='[]'),
        ),
    ]
