# Generated by Django 3.2 on 2021-05-09 16:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0004_alter_upvote_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='votes',
            field=models.ManyToManyField(blank=True, related_name='vote_count', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Upvote',
        ),
    ]
