# Generated by Django 3.2.7 on 2021-09-06 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_alter_interest_keytags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='keytags',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
    ]
