# Generated by Django 3.2.7 on 2021-09-06 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_alter_interest_keytags'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='quest',
            index=models.Index(fields=['date_asked', 'asked_by', 'title', 'tags'], name='community_q_date_as_804ae4_idx'),
        ),
    ]
