# Generated by Django 3.2 on 2021-05-13 18:36

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_answer_votes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='body',
            field=tinymce.models.HTMLField(),
        ),
    ]
