# Generated by Django 3.2.7 on 2021-09-17 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0007_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
