# Generated by Django 3.2 on 2021-05-13 19:27

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0007_alter_quest_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='body',
            field=tinymce.models.HTMLField(verbose_name='Content'),
        ),
    ]
