# Generated by Django 3.2 on 2021-05-13 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0011_alter_quest_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='body',
            field=models.TextField(),
        ),
    ]
