# Generated by Django 3.2.9 on 2021-11-27 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chakra',
            name='value',
            field=models.FloatField(default=200),
        ),
    ]
