# Generated by Django 3.2.7 on 2021-09-27 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_chakra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chakra',
            name='value',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10),
        ),
    ]
