# Generated by Django 3.2.7 on 2021-09-27 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_chakra_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chakra',
            name='value',
            field=models.FloatField(default=10),
        ),
    ]
