# Generated by Django 2.2.3 on 2019-11-14 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CHM101',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('option_A', models.CharField(max_length=250)),
                ('option_B', models.CharField(max_length=250)),
                ('option_C', models.CharField(max_length=250)),
                ('option_D', models.CharField(max_length=250)),
                ('explanation', models.TextField()),
                ('is_correct', models.CharField(choices=[('option_A', 'option_A'), ('option_B', 'option_B'), ('option_C', 'option_C'), ('option_D', 'option_D')], default='option_A', max_length=250)),
            ],
        ),
    ]
