# Generated by Django 3.0 on 2020-01-07 16:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cbt', '0004_remove_question_question_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_symbol',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
