# Generated by Django 3.0 on 2020-05-09 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbt', '0007_premium'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Premium',
        ),
    ]
