# Generated by Django 3.0 on 2020-05-12 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbt', '0008_delete_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='premium',
            field=models.BooleanField(default=False, help_text='If yes, only premium users will be able to take the quiz'),
        ),
    ]
