# Generated by Django 3.2.9 on 2021-11-27 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbt', '0002_quiz_premium'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='premium',
        ),
    ]
