# Generated by Django 3.2.9 on 2021-11-27 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbt', '0003_remove_quiz_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='premium',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
